name: Release
on:
  push:
    tags: [ "*" ]
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/setup-action@v1
        with:
          jvm: zulu:11
          apps: sbt scala scalafmt
      - run: sbt -Dsun.net.client.defaultReadTimeout=60000 -Dsun.net.client.defaultConnectTimeout=60000 -Dspark.version=3.5.3 -v ci-release
        env:
          PGP_PASSPHRASE: ${{secrets.PGP_PASSPHRASE}}
          PGP_SECRET: ${{secrets.PGP_SECRET}}
          SONATYPE_PASSWORD: ${{secrets.SONATYPE_PASSWORD}}
          SONATYPE_USERNAME: ${{secrets.SONATYPE_USERNAME}}
